### ISSUE TITLE
Add ability for `yarn` to replace `bower` executable

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-try#102]
Would it be possible, if the `bower` executable was not found but `yarn` was, to use Yarn instead to install the alternate `bower` dependencies?  I'm in the process of replacing `npm` with `yarn` for the CI setups in many of my addons, and realized that it would be nice to just forgot that `bower` exists entirely and use `yarn` for that too 😬 

It seems like Bower support in Yarn is rocky right now, but after it stabilizes I'd be happy to add this support myself.

**Comment by nathanhammond** [comment]
@alexlafroscia We are investigating Yarn but will make no motion toward that until we have done a significant amount of testing and can be sure that they have a [compatible LTS story](https://github.com/yarnpkg/rfcs/pull/1).

I'm closing this issue for now as it's something we're closely monitoring but are unable to act on at this time. We'll be glad to tap you to help with that effort if it ever becomes time!

**Comment by wagenet** [comment]
Any updates?

**Comment by wagenet** [comment]
Looks like it is supported, didn't read enough of the README :)
