### ISSUE TITLE
Failing in Travis with `Error: Cannot find module './../utils/result-summary'`

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-try#121]
I'm seeing this in all my addons `Error: Cannot find module './../utils/result-summary'`.

It was after updating to ember-cli-babel 6.0.0-beta.9, so unsure if that is causing the issue or not.

**Comment by rwjblue** [comment]
Seems like it may be a botched install, can you clear `node_modules` and cache and reinstall?

**Comment by kategengler** [comment]
@rwwagner90 Thought I should mention here that @rwjblue and I chatted about this and think we know what it is. Unfortunately wasn't able to get to fixing it today, but should be able to take a look tomorrow.

Workarounds for now: Pin ember-try to 0.2.11 OR use yarn to install in CI.

**Comment by marcoow** [comment]
We're seeing this for ember-cookies builds as well: https://travis-ci.org/simplabs/ember-cookies/builds/215337080. Only seems to occur for Node 4 builds, Node 7 works fine.
