### ISSUE TITLE
npm@5 issues

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-try#130]
Not 100% sure, but it seems if `npm@5` is installed ember-try becomes unhappy but without it installed all appears well.

~~We should likely get ahead of this (before npm 5 ships)~~ we likely need to fix this ;)

**Comment by rwjblue** [comment]
FYI - npm 5 has already shipped as `latest` (a few days ago).

**Comment by stefanpenner** [comment]
related: https://github.com/ember-cli/ember-cli/issues/7082

**Comment by stefanpenner** [comment]
I can no longer reproduce, lets hope that means I merely trolled myself.
