### ISSUE TITLE
bower version

### ISSUE THREAD

**Issue by jlami** [ember-cli/ember-try#131]
Hi,

I don't know if this is a Windows only problem. But the way you check for bower and then install it might need a little tweaking: https://github.com/ember-cli/ember-try/blob/master/lib/dependency-manager-adapters/bower.js#L194
The `npm install bower@^1.3.12` should be shell escaped, or the ^ will be ignored. So `npm install bower@"^1.3.12"` would be better. Now version 1.3.12 is always installed.

But further more you ignore global installations of bower.
I don't know how to check for these, but maybe just checking if `bower --version` generates something logical? Or maybe --link with the npm install bower can help?

**Comment by kategengler** [comment]
This code has been removed, in favor of adding bower implicitly to the scenarios that require it, in #157
