### ISSUE TITLE
ember-cli module directory emptied of files

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-try#141]
When using a `yarn.lock` but without bower as a dependency in `package.json`, the `node_modules/ember-cli/` is emptied of files.

* Failed build with error: https://circleci.com/gh/Vestorly/torii/614
* Successful build: https://circleci.com/gh/Vestorly/torii/615 
* Only change to fix was adding bower to `package.json`: https://github.com/Vestorly/torii/pull/382/commits/43d9737b617a5a555b5d325e23fe7ad23961997f

Currently when `yarn` is detected ember-try attempts to use it for most operations. An exception is that if bower is not a dependency, `npm` is used to install that dependency. I presume there is some negative interaction between the two systems that causes the files to be deleted.

**Comment by kategengler** [comment]
Installing bower as-needed came in with https://github.com/ember-cli/ember-try/pull/109

I wonder if having bower scenarios should require a global bower? Now that I think on it more installing bower for each scenario is kinda sucky (for more reasons than this bug). Thoughts @rwjblue @Turbo87?

**Comment by rwjblue** [comment]
@kategengler - Agreed. Lets use global bower, and error if not present and `bower` key in config is present.

**Comment by rwjblue** [comment]
FWIW, I've been fighting with this issue today as well. I believe that it only happens when using `npm@5` (in my case downgrading to `npm@4` resolved the error `cannot find module 'ember-cli'`).

**Comment by kellyselden** [comment]
I don't think it's that easy. Even though we removed bower as a requirement in our docs, most of the scenarios in the addon default blueprint use bower to resolve ember. (Newer) add-ons would start to get errors in CI if we switched to global bower. I suppose we could mitigate this by adding back a global install of bower in our default .travis.yml.

**Comment by Turbo87** [comment]
> I wonder if having bower scenarios should require a global bower?

for CLI itself we can't do that since we use `bower` programmatically and you can't do that with a global install

**Comment by billy-addepar** [comment]
I got this error while running tests with ember try:

> The command ember t exited Error: Cannot find module 'ember-cli'

I am on `5.3.0` npm and do not want to downgrade npm. Could my error possibly be related to this issue?

**Comment by mixonic** [comment]
Argh, just hit this a second time and spent another few hours debugging 😭

**Comment by kategengler** [comment]
Exact steps to recreate here:

Using npm > 5:
1) `ember addon try-test-addon-yarn --yarn true`
2) Edit `config/ember-try.js` to add `useYarn: true`
3) `ember try:each`
