### ISSUE TITLE
`ember try:each` does not cleanup a bower.json if one didn't previously exist

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-try#142]
By default Ember addons have no `bower.json` file, but one is created for certain scenarios.  

Currently, after running `ember try:each` the working directory still contains a `bower.json`.  This exact scenario should have been resolved by https://github.com/ember-cli/ember-try/pull/115...

**Comment by kategengler** [comment]
Disturbingly, there is an acceptance-style test for just this https://github.com/ember-cli/ember-try/blob/master/test/tasks/try-each-test.js#L213

**Comment by kategengler** [comment]
The only way I've been able to reproduce this is on killed or broken ember-try runs. Can you reproduce this on successful ember-try runs?

**Comment by efx** [comment]
While upgrading ember-page-title dependencies, I observed this issue. You can see the error occur after the test suite passed: https://travis-ci.org/adopted-ember-addons/ember-page-title/jobs/544790578

**Comment by kategengler** [comment]
@efx I believe you hit a different issue than this is -- this is an issue when ember-try scenarios use bower but the host project does not. 

The issue of an empty bower.json causing the error you saw is another one (that I cannot find at the moment).

**Comment by rwjblue** [comment]
Bower support has been removed, closing...
