### ISSUE TITLE
Ignore package-lock.json by default

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-try#144]
We should run with `--no-shrinkwrap` by default on `npm install`, which ignores `npm-shrinkwrap.json` and `package-lock.json` and does not generate `package-lock.json`

We did this with yarn, because for most uses of `ember-try`, we want the scenarios to get the latest of the packages available and version drift is sometimes necessary for the changes made in the scenarios to even work.

**Comment by rwjblue** [comment]
I thought we do this already?

**Comment by kategengler** [comment]
No? We do it for yarn.
