### ISSUE TITLE
`useYarn: true` causes `ember try:each` to fail

### ISSUE THREAD

**Issue by alexdiliberto** [ember-cli/ember-try#147]
Steps to reproduce:

```bash
# Create a new addon
ember addon test-addon --yarn

# Now add `useYarn: true` to `config/ember-try.js`

# Now test
yarn test

# ...Error on the first test run
````
```bash
...

=== Scenario: ember-lts-2.8 ====================================================

Error!
The command ember test exited Error: Cannot find module 'ember-cli' from '/Users/alexdiliberto/Repos/temp/test-addon'
undefined
error Command failed with exit code 1.
```

Remove `useYarn: true` and it works again

```bash
$ ember v --verbose
ember-cli: 2.15.0
http_parser: 2.7.0
node: 6.11.2
v8: 5.1.281.103
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2l
os: darwin x64
```

**Comment by kategengler** [comment]
`useYarn: true` in not yet released. Did you specifically point to ember-cli/ember-try master?

**Comment by alexdiliberto** [comment]
@kategengler Agh oh, it's in the README. I just figured it was in stable release

**Comment by noslouch** [comment]
It's also printed out to the screen when running `ember try:each` with ember-cli 2.15.1.

![image](https://user-images.githubusercontent.com/2090382/30516132-27a5d93a-9b04-11e7-8835-bed4c074f3e6.png)

**Comment by varoot** [comment]
Is this supposed to be working? I got the same error. My ember-try version is `0.2.17` according to `yarn.lock`. Ember CLI 2.16.2
