### ISSUE TITLE
Scenarios missing their deps when no bower and no package-lock.json

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-try#150]
If your app does not have bower and does not have a package-lock.json, it's possible to get into a state where `ember-try` installs `bower` while accidentally producing a package-lock.json that *only* contains bower. 

Then apparently during scenario setup it respects the package-lock.json and you end up missing all your packages.

**Comment by rwjblue** [comment]
Yes, ember-try + npm@5 is a very bad experience at the moment.
