### ISSUE TITLE
`npm prune --no-shrinkwrap` removes packages declared with `github:repo#hash` syntax

### ISSUE THREAD

**Issue by xcambar** [ember-cli/ember-try#170]
Since 0.2.18 and the introduction of the `--no-shrinkwrap` to the `npm prune` command (see https://github.com/ember-cli/ember-try/blob/23bc1e62845f1786026bde54eb9a53a996003d95/lib/dependency-manager-adapters/npm.js#L111-L113), **some** packages declared with the `github:org/repo#commitish` syntax are removed.

I doubt this is an `ember-try` bug, as the results vary from one platform to another and I've narrowed it down to the `npm prune --no-shrinkwap` command.

The questions at hand here are:

* Did anyone else notice this behaviour?
* The `--no-shrinkwrap` argument to `npm prune` is undocumented, is it safe for use?
* Could the same outcome be obtained differently?

FWIW, I've created a repo which test command replicates the issue: https://github.com/xcambar/npm-prune

**Comment by xcambar** [comment]
See https://github.com/npm/npm/issues/19522 for the corresponding ticket in npm

**Comment by kategengler** [comment]
It is a mistake/bug that `--no-shrinkwrap` is passed to prune as well as install. However, this is the first I've heard anybody mention problems with it. I believe that `npm prune` without the `--no-shrinkwrap` option should do what ember-try needs there, but that does need to be tested.

@xcambar Can you confirm that `npm prune` without `--no-shrinkwrap` does not cause you the same problem?

**Comment by kategengler** [comment]
Fixed by #171
