### ISSUE TITLE
Remove "default config"?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-try#177]
This seemed like a good feature at the time, but now it feels a bit odd to me. I think that the version compatibility feature is likely a better path forward for those trying to reduce the configuration burden...

Any objections?

**Comment by kategengler** [comment]
No and I don't think anybody uses it.

**Comment by Turbo87** [comment]
@rwjblue not sure what `default config` means 🤔

**Comment by rwjblue** [comment]
If you don’t have a config/ember-try.js but you run an `ember try...` command we use a “default config”.  I think we should remove that...

**Comment by Turbo87** [comment]
ah, okay, I thought it was something else. glad I asked... kill it! :)
