### ISSUE TITLE
Pass additional arguments to yarn

### ISSUE THREAD

**Issue by andreyfel** [ember-cli/ember-try#188]
I need to skip optional dependencies on the yarn install phase to reduce time of the build. So, I need to run yarn install with "--ignore-optional" argument.
Generic solution for this issue would be to be able to configure yarn options.
I tried to use npmOptions parameter from the ember-try config but seems it is not respected when useYarn is set to true.

**Comment by kategengler** [comment]
`npmOptions` should be used with useYarn as well. Can you run with `DEBUG=ember-try* <your ember-try command>` to get output that will tell us what command is being run?

**Comment by kategengler** [comment]
@andreyfel Is this still happening?

**Comment by rwjblue** [comment]
FWIW #409 made it possible to control **exactly** what is passed in to each of the dependency managers. I'm going to close now, but if folks still think this is a bug I'm happy to reopen.
