### ISSUE TITLE
Keep .node_modules.ember-try from being accidentally published

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-try#189]
Ideas:

- Move to system temp (+ make configurable location)
- Write a .npmignore in the directory

**Comment by rwjblue** [comment]
> Write a .npmignore in the directory

Does this work? I wasn't aware you could just sprinkle `.npmignore` files around...

>  Move to system temp (+ make configurable location)

Seems like a good option to me...

**Comment by kategengler** [comment]
>Does this work? I wasn't aware you could just sprinkle .npmignore files around...

Docs I read implied you could nest .npmignore files but I would test it first.
