### ISSUE TITLE
A function in the Route to just leave current route, whatever it is.

### ISSUE THREAD

**Issue by Benjy1979** [ember-cli/ember-try#199]
Hi,

It would be nice to have a function that leaves the current route and goes back up to the parent route using all the same parameters.

Like in the router, if I have afterModel(model, transition) , I may want to immediately leave the route after the route has done something in particular but it's a bit contrived to have to spell out the full route path in this.transitionTo('route1.route2.route3') etc

The code would be more reusable if you could just say:"this.leaveCurrentRoute() or just this.exitRoute() or this.leave()", blind to what route it actually is.

Thanks.

**Comment by rwjblue** [comment]
Hmm, I don't fully understand how this relates to ember-try?

**Comment by Benjy1979** [comment]
Oops sorry. Completely commented on the wrong page.

**Comment by rwjblue** [comment]
No problem! Closing...
