### ISSUE TITLE
"Cannot find module 'bower'" after a succesful test run with an addon that doesn't use bower

### ISSUE THREAD

**Issue by kybishop** [ember-cli/ember-try#212]
https://travis-ci.org/kybishop/ember-attacher/jobs/440774809

I'm seeing a bower-related error in Travis after attempting to upgrade my addon to 3.4 (from 3.0).

This is a bit confusing since my addon hasn't used bower in a long time, maybe not even ever.

If helpful, here is the WIP PR https://github.com/kybishop/ember-attacher/pull/153

**Comment by kybishop** [comment]
Figured it out, though I'm still not sure why it happens in the first place:

The new ember-try config blueprint removes --skip-cleanup from the travis run. I guess this kicks off something that includes bower. Added --skip-cleanup back in and all good.

**Comment by tsteuwer** [comment]
@kybishop thank you so much! I'm having this **exact** same issue on https://github.com/tsteuwer/ember-tracker and all the versions I'm testing are 3.2+. Will try your fix for now...

**Comment by tsteuwer** [comment]
This may be the same thing as #142

**Comment by rwjblue** [comment]
Sorry we never nailed this down, bower support has been fully removed now.
