### ISSUE TITLE
Bower ember version not used when ember-source defined as devDependency in addon

### ISSUE THREAD

**Issue by mistahenry** [ember-cli/ember-try#234]
It appears when running `ember-try` scenarios that depend on a `bower` ember dependency, the `node-modules` version of the `ember-source` defined in an addon's `devDependencies` is used instead. Here is a [reproduction](https://github.com/mistahenry/ember-try-bower-ignored-reproduction). If you remove the `ember-source` dependency, then the `bower` version is actually used.

Reproduced with:
```sh
ember-cli: 3.5.1
node: 8.11.3
os: darwin x64
```

Just to prove to myself that this was really happening, I ran acceptance tests against a route  that used contextual components. I then used a scenario for ember 2.2 and they all passed when I had `ember-source: 3.5.1` in my `node_modules`. As soon as I removed this `ember-source` and ran the test again, I got the expected errors with contextual components

**Comment by mistahenry** [comment]
I looked into this some more and if you pass 

```javascript
npm: {
  devDependencies: {
    'ember-source': null
   }
 }
```

then the bower version of ember is used. 

On the one hand, given how `ember-cli` determines which [ember version to use](https://github.com/ember-cli/ember-cli/blob/f194d52232739dd3d6a4184b3cab8ceac791476f/lib/broccoli/ember-app.js#L405) (or at least what looks like it to me from a glance), it seems understandable that this is happening. Is this the intent? If so, it should definitely be documented.

I worry that addons think they're testing against old ember versions but never actually drop below 2.12 despite having scenarios.

Would `ember-try` be open to a PR that detects if a bower `ember` version is passed in the scenario that autoadds the above `ember-source: null` npm dependency?

**Comment by kategengler** [comment]
The default scenarios that tested below `npm` version of ember did indeed have the required 
```npm: {
  devDependencies: {
    'ember-source': null
   }
 }
``` configuration. 

Using the `versionCompatibility` feature will also automatically get this behavior (https://github.com/ember-cli/ember-try-config/blob/master/lib/auto-scenario-config-for-ember.js#L45).

That said, no currently supported version of Ember is unavailable via `npm`. The last LTS version of Ember only supported on Bower (2.8) [stopped receiving bugfixes in June 2017, and security fixes in February 2018](https://www.emberjs.com/blog/2017/11/20/ember-2-17-released.html#toc_ember-js-2-16-lts).

It seems unreasonable to expect addon maintainers to support versions that Ember itself does not support, and has not for a very long time.

**Comment by mistahenry** [comment]
>It seems unreasonable to expect addon maintainers to support versions that Ember itself does not support

This is this addon's documented example that won't do what it's supposed to if you have a local npm version of ember.

```javascript
{
    name: 'Ember 1.10 with ember-data',

    /*
      `command` can also be overridden at the scenario level.
    */
    command: 'ember test --filter ember-1-10',
    bower: {
      dependencies: {
        'ember': '1.10.0',
        'ember-data': '1.0.0-beta.15'
      }
    }
}
```

How am I being unreasonable by thinking that's still supported? It seems like you might have missed the part where I said: 

>Would ember-try be open to a PR that detects if a bower ember version is passed in the scenario that autoadds the above ember-source: null npm dependency?

This was me offering to fix it, but I wanted to hear from a maintainer here first if you'd rather I just fix the documentation that's wrong or try to fix internally. 

I completely disagree with your logic about support dropping, though. Ember can do what they want, but that doesn't mean every app out there has the luxury of updating. There are domains with excessive amounts of compliance that add an unbelievable amount of friction to updates (banking for one). 

I think they're are a lot of addons out there that would like to support as far back in Ember as possible so that old apps can still continue to receive the improvements they offer over time. `ember-try` is the tool to know if you should *then* decide to drop support when something gets difficult.

**Comment by kategengler** [comment]
The documentation example has been carried forward over a long time. 

I'd prefer to fix it in documentation because 1) using the `versionCompatibility` feature of ember-try does it correctly and 2) The scenarios provided by ember-cli's [blueprint](https://github.com/ember-cli/ember-addon-output/blob/v2.12.0/config/ember-try.js#L5) once ember-source became the default correctly removed ember-source from the scenarios.
