### ISSUE TITLE
Ember Data config not working

### ISSUE THREAD

**Issue by mikkopaderes** [ember-cli/ember-try#334]
Is this the appropriate ember-try config for the beta version of ember-data?

```javascript
{
  name: 'ember-beta',
  npm: {
    devDependencies: {
      'ember-data': 'beta',
      'ember-source': urls[1]
    }
  }
},
```

I can't seem to make it work, I used to do `emberjs/data#beta` which was working fine before but not anymore.

[Here's](https://travis-ci.org/mikkopaderes/ember-cloud-firestore-adapter/jobs/528407109) my Travis log

**Comment by kategengler** [comment]
This was due to a change in how ember-data structures it's repo. More info here https://github.com/emberjs/data/issues/6010
