### ISSUE TITLE
`ember-try-config` messing with shrinkwrap

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-try#80]
I have a project using `npm shrinkwrap --dev` and it's getting hung up on `ember-try-config` due to the fact that it is specified as `latest`.  I keep getting errors that say that I have the wrong version, presumably because it's expected the version `latest` and I don't have a version that is literally called that.

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have ember-try-config@2.0.1 (expected: latest) /Users/alexlafroscia/Code/my-app/src/frontend/node_modules/ember-cli/node_modules/ember-try/node_modules/ember-try-config
npm ERR! extraneous: ember-try-config@2.0.1 /Users/alexlafroscia/Code/my-app/wwn/src/frontend/node_modules/ember-cli/node_modules/ember-try/node_modules/ember-try-config
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alexlafroscia/Code/my-app/src/frontend/npm-debug.log
```

I know that we probably shouldn't be doing `npm shrinkwrap --dev` but that's out of my hands... Is there a possibility that you could specify that version differently?

**Comment by cibernox** [comment]
Even without shinkwrap, there is some combinations of addons that make ember-cli-dependency-checker fail and apps cannot run.
Since ember-try is included in ember-cli now, that means that because of this dogdy dependency version, ember-cli is broken.

This is a **very serious problem**.

**Comment by kategengler** [comment]
This should be handled by #85 now, thanks to @cibernox 

@cibernox Do you have any more info on the combinations of addons that cause problems?

**Comment by kategengler** [comment]
Closing since this is resolved.
