### ISSUE TITLE
Allow scenarios without dependency changes

### ISSUE THREAD

**Issue by trentmwillis** [ember-cli/ember-try#81]
Currently, [the `ScenarioManager` checks to ensure that there are dependency managers](https://github.com/ember-cli/ember-try/blob/master/lib/utils/scenario-manager.js#L15) which are only created if you specify [some sort of dependency change](https://github.com/ember-cli/ember-try/blob/master/lib/utils/dependency-manager-adapter-factory.js#L16-L21) in your scenarios.

However, I have [a use-case](https://github.com/trentmwillis/ember-exam/issues/41) where I would like to run multiple different scenarios without changing any dependencies. This currently results in a `No dependency manager adapter` error being thrown. I can workaround this by specifying an empty dependency change (e.g., `npm: {}`), but this feels hacky.

So, I have two questions:
1. Why is there a requirement that dependency managers must be present currently?
2. Can we remove that requirement? It seems like answer should be yes since I can hack around it now anyway.

**Comment by rwjblue** [comment]
Yes. It should not be required. It makes sense to have various scenarios (possibly with the project default deps) for different commands and stuff.

**Comment by trentmwillis** [comment]
Sounds good, will open a PR then.

**Comment by kategengler** [comment]
@trentmwillis Is this still desired?

**Comment by trentmwillis** [comment]
I found a way to do what I want, but I feel like this could still be beneficial, just haven't had the time to do it

**Comment by rwjblue** [comment]
I believe this is possible now (and a scenario without dependency changes is part of the [default addon blueprint](https://github.com/ember-cli/ember-addon-output/blob/v2.15.0-beta.2/config/ember-try.js#L76-L81)).

Closing...

**Comment by kategengler** [comment]
I think what was meant was a scenario without either npm or bower. @mixonic also asked about this recently in slack.

**Comment by trentmwillis** [comment]
Yes, the original issue was to have different scenarios (say with different commands), but without _any_ dependency changes.

**Comment by mixonic** [comment]
Specifically I've found myself in the ember-resolver and in a client app wanting to run scenarios that are based on ENV variables. No dependencies to change, just different commands to run.

**Comment by rwjblue** [comment]
Hmm.  I guess I don't fully grok what y'all mean.  

The following config does not do any dependency changes and has a custom command per-scenario:

```js
module.exports = [
  { 
    name: 'default',
    command: 'ember test'
    npm: {},
    bower: {}
  },
  { 
    name: 'special-sauce',
    command: 'SPECIAL_SAUCE=true ember test'
    npm: {},
    bower: {}
  }
]
```

What am I missing?

**Comment by rwjblue** [comment]
(reopening because it seems that I must be misunderstanding...)

**Comment by trentmwillis** [comment]
@rwjblue your example is correct, but you should able to do this without needing to specify `npm` or `bower` fields. In other words, you should be able to specify a scenario like so without an error:

```
{ 
  name: 'special-sauce',
  command: 'SPECIAL_SAUCE=true ember test'
}
```

**Comment by rwjblue** [comment]
AHA! OK! Sorry, I was over-focusing on the fact that it was _possible_ and didn't realize we were mostly just talking about the ergonomics.

I think we can just remove the error when there are no managers: https://github.com/ember-cli/ember-try/pull/143.

**Comment by trentmwillis** [comment]
No worries! Thanks for opening the PR :)
