### ISSUE TITLE
Allow user to disable beta, canary when using versionCompatability

### ISSUE THREAD

**Issue by martndemus** [ember-cli/ember-try#86]
My test suite on beta/canary right now is running into an infinite loop (due to an Ember.js bug), causing it to run for 59 minutes until Travis CI kills it.

**Comment by kategengler** [comment]
Would love a PR to handle an enabled option on each scenario, for now, as a hack, you could use something like this config:

```
/*jshint node:true*/

module.exports = function() {
  return {
    useVersionCompatibility: true,
    scenarios: [
      {
        name: 'ember-beta',
        command: './fail.sh'
      },
      {
        name: 'ember-canary',
        command: 'echo DISABLED'
      }
    ]};
};

```

When the config has `useVersionCompatibility: true` the scenarios will merge with the auto-generated ones. Run `ember try:config` to see what config it will run with. 

You can override the command to something harmless like `echo` or make a script that exits non-zero to fail the scenario.

**Comment by martndemus** [comment]
Hey thanks! That worked and is a totally fine for a temp fix! :)

**Comment by kategengler** [comment]
Closing as it should be covered by the solution to #155
