### ISSUE TITLE
Be smart about versions of Ember where version is provided by bower and where versions are provided by npm

### ISSUE THREAD

**Issue by kategengler** [ember-cli/ember-try#91]
Related to https://github.com/emberjs/ember.js/pull/13022

Older versions of ember need to be provided by bower. Newer versions will be provided by `npm`. 

`versionCompatibility` way of running should be made to just do the right thing. 

Manual config should have `ember` under the correct key. Update blueprint in ember-cli (or switch to version compatibility by default).

**Comment by kategengler** [comment]
With #108, configuration for using ember-source should be possible. Used here: https://github.com/emberobserver/client/blob/master/config/ember-try.js#L30,  but tests are failing so I'm not sure I've switched over entirely right. 

Still need to determine what canary and beta look like from npm.

**Comment by broerse** [comment]
We now have beta it seems. `npm view ember-source dist-tags`

**Comment by broerse** [comment]
There is an issue related to this.

https://github.com/ember-cli/ember-try/issues/91

**Comment by kategengler** [comment]
We did this!

**Comment by broerse** [comment]
@kategengler We love it!
