### ISSUE TITLE
ember-try seems to be broken in Ember beta/canary

### ISSUE THREAD

**Issue by elwayman02** [ember-cli/ember-try#944]
I've been seeing this crop up across all my projects over the last month or so. Something changed in ember-canary that started throwing this error, and it's been promoted to ember-beta within the last week or so. The error seems to lead back to how ember-try is using fs-extra somehow.

Here's an example:

https://github.com/elwayman02/ember-resize-modifier/actions/runs/4658059719/jobs/8243330137?pr=707

```
Error cleaning up npm scenario: Error: Cannot copy '../../../../../esprima/bin/esvalidate.js' to a subdirectory of itself, '../../../../../esprima/bin/esvalidate.js'.
    at /home/runner/work/ember-resize-modifier/ember-resize-modifier/node_modules/ember-try/node_modules/fs-extra/lib/copy/copy.js:210:21
```

**Comment by kategengler** [comment]
It is not canary. See #813 and try the 3.0.0-beta.1 of ember-try.

**Comment by elwayman02** [comment]
Awesome, thanks for noting. I'll close and track that issue instead.
