### ISSUE TITLE
Running command silently contains ember-try installation output

### ISSUE THREAD

**Issue by gmurphey** [ember-cli/ember-try#99]
I'm writing a scenario to test internal, unpublished dependencies and running the following command in our CI environment:

`ember try:one development --- ember test -r xunit --silent > test-log.xml`

This seemingly runs without issue, but when we try to parse that file, we find that some `ember-try` output is appended and prepended to the file.

    bower ember#~2.8.0              cached https://github.com/components/ember.git#2.8.1
    ...more bower installation output...

    ...xunit xml output...

    ...more bower rollback output....
    bower jquery#>=1.8.3                                       cached https://github.com/jquery/jquery-dist.git#3.1.1

I'm happy to dig into this. Just wanted to put it out there if anyone else had ideas on what this could be.

**Comment by gmurphey** [comment]
I was able to handle this more cleanly with `testem.js`.

**Comment by kategengler** [comment]
For anybody running into this in the future:

After #107 lands:

`ember try:one development --- ember test -r xunit --silent > test-log.xml` puts the output of the `ember try` command into test-log.xml

But, this:
`ember try:one development --- 'ember test -r xunit --silent > test-log.xml'` will put the output of just the test command into test-log.xml
